"""Deterministic HMAC integrity envelopes for controlled JSON exports.

These envelopes prove that a payload was generated by a holder of the configured
server key and has not changed. They are not a legal digital signature or a
public-key certificate.
"""

from __future__ import annotations

import hashlib
import hmac
import json
from typing import Any


def canonical_json_bytes(payload: Any) -> bytes:
    return json.dumps(
        payload,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=False,
        default=str,
    ).encode("utf-8")


def sign_integrity_payload(payload: Any, signing_key: str) -> dict[str, str]:
    if len(signing_key) < 32:
        raise ValueError("Signing key must contain at least 32 characters")
    canonical = canonical_json_bytes(payload)
    key_bytes = signing_key.encode("utf-8")
    return {
        "algorithm": "HMAC-SHA256",
        "value": hmac.new(key_bytes, canonical, hashlib.sha256).hexdigest(),
        "key_id": hashlib.sha256(key_bytes).hexdigest()[:16],
    }


def verify_integrity_payload(
    payload: Any,
    signature: str,
    signing_key: str,
) -> bool:
    expected = sign_integrity_payload(payload, signing_key)["value"]
    return hmac.compare_digest(expected, signature)
